/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model


import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param oldPassword
 * @param newPassword
 */
@Parcelize
@KSerializable

data class ChangePassword(

    @SerialName(value = "oldPassword")
    val oldPassword: kotlin.String,

    @SerialName(value = "newPassword")
    val newPassword: kotlin.String

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

