/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param race
 * @param name
 * @param world
 * @param id
 * @param datacenter
 * @param customFields
 * @param freeCompany
 */
@Parcelize
@KSerializable

data class Character(

    @Contextual @SerialName(value = "race")
    val race: CharacterRace,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "world")
    val world: kotlin.String,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "datacenter")
    val datacenter: kotlin.String? = null,

    @SerialName(value = "customFields")
    val customFields: kotlin.collections.List<CustomField>? = null,

    @SerialName(value = "freeCompany")
    val freeCompany: FreeCompany? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

