/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "unused"
)

package app.bambushain.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: hyur,elezen,lalafell,miqote,roegadyn,auRa,hrothgar,viera
 */
@Serializable
enum class CharacterRace(val value: kotlin.String) {

    @SerialName(value = "hyur")
    hyur("hyur"),

    @SerialName(value = "elezen")
    elezen("elezen"),

    @SerialName(value = "lalafell")
    lalafell("lalafell"),

    @SerialName(value = "miqote")
    miqote("miqote"),

    @SerialName(value = "roegadyn")
    roegadyn("roegadyn"),

    @SerialName(value = "au-ra")
    auRa("au-ra"),

    @SerialName(value = "hrothgar")
    hrothgar("hrothgar"),

    @SerialName(value = "viera")
    viera("viera");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CharacterRace) "$data" else null

        /**
         * Returns a valid [CharacterRace] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CharacterRace? = data?.let {
            val normalizedData = "$it".lowercase()
            entries.firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}


