/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "unused"
)

package app.bambushain.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: carpenter,blacksmith,armorer,goldsmith,leatherworker,weaver,alchemist
 */
@Serializable
enum class CrafterJob(val value: kotlin.String) {

    @SerialName(value = "carpenter")
    carpenter("carpenter"),

    @SerialName(value = "blacksmith")
    blacksmith("blacksmith"),

    @SerialName(value = "armorer")
    armorer("armorer"),

    @SerialName(value = "goldsmith")
    goldsmith("goldsmith"),

    @SerialName(value = "leatherworker")
    leatherworker("leatherworker"),

    @SerialName(value = "weaver")
    weaver("weaver"),

    @SerialName(value = "alchemist")
    alchemist("alchemist");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CrafterJob) "$data" else null

        /**
         * Returns a valid [CrafterJob] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CrafterJob? = data?.let {
            val normalizedData = "$it".lowercase()
            entries.firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}


