/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param id
 * @param label
 * @param position
 * @param options
 */
@Parcelize
@KSerializable

data class CustomField(

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "label")
    val label: kotlin.String? = null,

    @SerialName(value = "position")
    val position: kotlin.Int? = null,

    @SerialName(value = "options")
    val options: kotlin.collections.List<CustomFieldOption>? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

