/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "unused"
)

package app.bambushain.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: paladin,warrior,darkKnight,gunbreaker,whiteMage,scholar,astrologian,sage,monk,dragoon,ninja,samurai,reaper,bard,machinist,dancer,blackMage,summoner,redMage,blueMage,viper,pictomancer
 */
@Serializable
enum class FighterJob(val value: kotlin.String) {

    @SerialName(value = "paladin")
    paladin("paladin"),

    @SerialName(value = "warrior")
    warrior("warrior"),

    @SerialName(value = "dark-knight")
    darkKnight("dark-knight"),

    @SerialName(value = "gunbreaker")
    gunbreaker("gunbreaker"),

    @SerialName(value = "white-mage")
    whiteMage("white-mage"),

    @SerialName(value = "scholar")
    scholar("scholar"),

    @SerialName(value = "astrologian")
    astrologian("astrologian"),

    @SerialName(value = "sage")
    sage("sage"),

    @SerialName(value = "monk")
    monk("monk"),

    @SerialName(value = "dragoon")
    dragoon("dragoon"),

    @SerialName(value = "ninja")
    ninja("ninja"),

    @SerialName(value = "samurai")
    samurai("samurai"),

    @SerialName(value = "reaper")
    reaper("reaper"),

    @SerialName(value = "bard")
    bard("bard"),

    @SerialName(value = "machinist")
    machinist("machinist"),

    @SerialName(value = "dancer")
    dancer("dancer"),

    @SerialName(value = "black_mage")
    blackMage("black_mage"),

    @SerialName(value = "summoner")
    summoner("summoner"),

    @SerialName(value = "red-mage")
    redMage("red-mage"),

    @SerialName(value = "blue-mage")
    blueMage("blue-mage"),

    @SerialName(value = "viper")
    viper("viper"),

    @SerialName(value = "pictomancer")
    pictomancer("pictomancer");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is FighterJob) "$data" else null

        /**
         * Returns a valid [FighterJob] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): FighterJob? = data?.let {
            val normalizedData = "$it".lowercase()
            entries.firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}


