/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param job
 * @param id
 * @param level
 * @param gearScore
 * @param characterId
 */
@Parcelize
@KSerializable

data class Fighter(

    @Contextual @SerialName(value = "job")
    val job: FighterJob,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "level")
    val level: kotlin.String? = null,

    @SerialName(value = "gearScore")
    val gearScore: kotlin.String? = null,

    @SerialName(value = "characterId")
    val characterId: kotlin.Int? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

