/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param district
 * @param ward
 * @param plot
 * @param id
 * @param freeCompanyId
 */
@Parcelize
@KSerializable

data class FreeCompanyHousing(

    @Contextual @SerialName(value = "district")
    val district: HousingDistrict,

    @SerialName(value = "ward")
    val ward: kotlin.Int,

    @SerialName(value = "plot")
    val plot: kotlin.Int,

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "freeCompanyId")
    val freeCompanyId: kotlin.Int? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

