/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RemoveEmptyClassBody"
)

package app.bambushain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param id
 * @param email
 * @param displayName
 * @param discordName
 * @param isMod
 * @param isBanned
 */
@Parcelize
@KSerializable

data class GroveUser(

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "displayName")
    val displayName: kotlin.String? = null,

    @SerialName(value = "discordName")
    val discordName: kotlin.String? = null,

    @SerialName(value = "isMod")
    val isMod: kotlin.Boolean? = null,

    @SerialName(value = "isBanned")
    val isBanned: kotlin.Boolean? = null

) : Serializable, Parcelable {
}

