/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param title
 * @param description
 * @param startDate
 * @param endDate
 * @param id
 * @param startTime
 * @param endTime
 * @param reminder
 */
@Parcelize
@KSerializable

data class GroveEvent(

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "description")
    val description: kotlin.String,

    @Contextual @SerialName(value = "startDate")
    val startDate: kotlinx.datetime.LocalDate,

    @Contextual @SerialName(value = "endDate")
    val endDate: kotlinx.datetime.LocalDate,

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @Contextual @SerialName(value = "startTime")
    val startTime: kotlinx.datetime.LocalTime? = null,

    @Contextual @SerialName(value = "endTime")
    val endTime: kotlinx.datetime.LocalTime? = null,

    @SerialName(value = "reminder")
    val reminder: kotlin.collections.List<EventReminder>? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

