/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model


import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param id
 * @param name
 * @param description
 * @param inviteEnabled
 * @param createdAt
 * @param updatedAt
 */
@Parcelize
@KSerializable

data class Grove(

    @Contextual @SerialName(value = "id")
    val id: java.util.UUID? = null,

    @SerialName(value = "name")
    val name: kotlin.String? = null,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "inviteEnabled")
    val inviteEnabled: kotlin.Boolean? = null,

    @Contextual @SerialName(value = "createdAt")
    val createdAt: kotlin.time.Instant? = null,

    @Contextual @SerialName(value = "updatedAt")
    val updatedAt: kotlin.time.Instant? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

