/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model


import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param groveId
 */
@Parcelize
@KSerializable

data class JoinGrove(

    @Contextual @SerialName(value = "groveId")
    val groveId: java.util.UUID

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

