/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "unused"
)

package app.bambushain.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: joined,notJoined,banned
 */
@Serializable
enum class JoinGroveStatus(val value: kotlin.String) {

    @SerialName(value = "joined")
    joined("joined"),

    @SerialName(value = "not-joined")
    notJoined("not-joined"),

    @SerialName(value = "banned")
    banned("banned");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? =
            if (data is JoinGroveStatus) "$data" else null

        /**
         * Returns a valid [JoinGroveStatus] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JoinGroveStatus? = data?.let {
            val normalizedData = "$it".lowercase()
            entries.firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}


