/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model


import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param email
 * @param displayName
 * @param discordName
 */
@Parcelize
@KSerializable

data class UpdateProfile(

    @SerialName(value = "email")
    val email: kotlin.String,

    @SerialName(value = "displayName")
    val displayName: kotlin.String,

    @SerialName(value = "discordName")
    val discordName: kotlin.String

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

