/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "DuplicatedCode",
    "RemoveRedundantQualifierName",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD"
)

package app.bambushain.model


import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.SerialName
import java.io.Serializable
import kotlinx.serialization.Serializable as KSerializable

/**
 * 
 *
 * @param id
 * @param email
 * @param displayName
 * @param discordName
 * @param appTotpEnabled
 * @param profilePicture
 */
@Parcelize
@KSerializable

data class User(

    @SerialName(value = "id")
    val id: kotlin.Int? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "displayName")
    val displayName: kotlin.String? = null,

    @SerialName(value = "discordName")
    val discordName: kotlin.String? = null,

    @SerialName(value = "appTotpEnabled")
    val appTotpEnabled: kotlin.Boolean? = null,

    @SerialName(value = "profilePicture")
    val profilePicture: kotlin.String? = null

) : Serializable, Parcelable {
    companion object {
        private const val serialVersionUID: Long = 123
    }


}

